// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbfoSLMg9SHYpKNMg-WbDMqwUkt42FCv8',
    appId: '1:119818098863:web:58ee8abe88d857ef711c5a',
    messagingSenderId: '119818098863',
    projectId: 'chitchatappbymehdi',
    authDomain: 'chitchatappbymehdi.firebaseapp.com',
    storageBucket: 'chitchatappbymehdi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYv5wjDyQOnbA0HlN9l7eqCOgdLV2fRoQ',
    appId: '1:119818098863:android:487526dd2663d345711c5a',
    messagingSenderId: '119818098863',
    projectId: 'chitchatappbymehdi',
    storageBucket: 'chitchatappbymehdi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkgo-Yy_4CLeR7a8zDxhs70TivrxBrvqg',
    appId: '1:119818098863:ios:a699f69864bb5565711c5a',
    messagingSenderId: '119818098863',
    projectId: 'chitchatappbymehdi',
    storageBucket: 'chitchatappbymehdi.appspot.com',
    iosBundleId: 'com.example.chitchatappbymehdinathani',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkgo-Yy_4CLeR7a8zDxhs70TivrxBrvqg',
    appId: '1:119818098863:ios:c0f2595200ef04e2711c5a',
    messagingSenderId: '119818098863',
    projectId: 'chitchatappbymehdi',
    storageBucket: 'chitchatappbymehdi.appspot.com',
    iosBundleId: 'com.example.chitchatappbymehdinathani.RunnerTests',
  );
}
